### ISSUE TITLE
Error building john

### ISSUE THREAD

**Issue by sman-dk** [anonion0/nsec3map#1]
Hi

When I run make I get the following error (I am trying to build john-1.8.0-jumbo-1 since I can not find john-1.7.9-jumbo8 on the homepage).

nsec3_gen_fmt_plug.c:314:2: warning: initialization makes integer from pointer without a cast [enabled by default]
nsec3_gen_fmt_plug.c:314:2: warning: (near initialization for ‘fmt_nsec3_gen.params.max_keys_per_crypt’) [enabled by default]
nsec3_gen_fmt_plug.c:314:2: error: initializer element is not computable at load time
nsec3_gen_fmt_plug.c:314:2: error: (near initialization for ‘fmt_nsec3_gen.params.max_keys_per_crypt’)
nsec3_gen_fmt_plug.c:316:3: warning: initialization from incompatible pointer type [enabled by default]
nsec3_gen_fmt_plug.c:316:3: warning: (near initialization for ‘fmt_nsec3_gen.methods.done’) [enabled by default]
nsec3_gen_fmt_plug.c:317:3: warning: initialization from incompatible pointer type [enabled by default]
nsec3_gen_fmt_plug.c:317:3: warning: (near initialization for ‘fmt_nsec3_gen.methods.reset’) [enabled by default]
nsec3_gen_fmt_plug.c:318:3: warning: initialization from incompatible pointer type [enabled by default]
nsec3_gen_fmt_plug.c:318:3: warning: (near initialization for ‘fmt_nsec3_gen.methods.prepare’) [enabled by default]
nsec3_gen_fmt_plug.c:319:3: warning: initialization from incompatible pointer type [enabled by default]
nsec3_gen_fmt_plug.c:319:3: warning: (near initialization for ‘fmt_nsec3_gen.methods.valid’) [enabled by default]
nsec3_gen_fmt_plug.c:320:3: warning: initialization from incompatible pointer type [enabled by default]
nsec3_gen_fmt_plug.c:320:3: warning: (near initialization for ‘fmt_nsec3_gen.methods.split’) [enabled by default]
nsec3_gen_fmt_plug.c:321:3: warning: braces around scalar initializer [enabled by default]
nsec3_gen_fmt_plug.c:321:3: warning: (near initialization for ‘fmt_nsec3_gen.methods.binary’) [enabled by default]
nsec3_gen_fmt_plug.c:322:4: warning: initialization from incompatible pointer type [enabled by default]
nsec3_gen_fmt_plug.c:322:4: warning: (near initialization for ‘fmt_nsec3_gen.methods.binary’) [enabled by default]
nsec3_gen_fmt_plug.c:323:4: warning: excess elements in scalar initializer [enabled by default]
nsec3_gen_fmt_plug.c:323:4: warning: (near initialization for ‘fmt_nsec3_gen.methods.binary’) [enabled by default]
nsec3_gen_fmt_plug.c:324:4: warning: excess elements in scalar initializer [enabled by default]
nsec3_gen_fmt_plug.c:324:4: warning: (near initialization for ‘fmt_nsec3_gen.methods.binary’) [enabled by default]
nsec3_gen_fmt_plug.c:325:4: warning: excess elements in scalar initializer [enabled by default]
nsec3_gen_fmt_plug.c:325:4: warning: (near initialization for ‘fmt_nsec3_gen.methods.binary’) [enabled by default]
nsec3_gen_fmt_plug.c:327:3: warning: excess elements in scalar initializer [enabled by default]
nsec3_gen_fmt_plug.c:327:3: warning: (near initialization for ‘fmt_nsec3_gen.methods.binary’) [enabled by default]
nsec3_gen_fmt_plug.c:328:3: warning: initialization from incompatible pointer type [enabled by default]
nsec3_gen_fmt_plug.c:328:3: warning: (near initialization for ‘fmt_nsec3_gen.methods.salt’) [enabled by default]
nsec3_gen_fmt_plug.c:329:3: warning: missing braces around initializer [-Wmissing-braces]
nsec3_gen_fmt_plug.c:329:3: warning: (near initialization for ‘fmt_nsec3_gen.methods.tunable_cost_value’) [-Wmissing-braces]
nsec3_gen_fmt_plug.c:329:3: warning: initialization from incompatible pointer type [enabled by default]
nsec3_gen_fmt_plug.c:329:3: warning: (near initialization for ‘fmt_nsec3_gen.methods.tunable_cost_value[0]’) [enabled by default]
nsec3_gen_fmt_plug.c:330:3: warning: initialization from incompatible pointer type [enabled by default]
nsec3_gen_fmt_plug.c:330:3: warning: (near initialization for ‘fmt_nsec3_gen.methods.tunable_cost_value[1]’) [enabled by default]
nsec3_gen_fmt_plug.c:331:3: warning: initialization from incompatible pointer type [enabled by default]
nsec3_gen_fmt_plug.c:331:3: warning: (near initialization for ‘fmt_nsec3_gen.methods.tunable_cost_value[2]’) [enabled by default]
nsec3_gen_fmt_plug.c:332:3: warning: initialization from incompatible pointer type [enabled by default]
nsec3_gen_fmt_plug.c:332:3: warning: (near initialization for ‘fmt_nsec3_gen.methods.source’) [enabled by default]
nsec3_gen_fmt_plug.c:333:3: warning: initialization from incompatible pointer type [enabled by default]
nsec3_gen_fmt_plug.c:333:3: warning: (near initialization for ‘fmt_nsec3_gen.methods.binary_hash[0]’) [enabled by default]
nsec3_gen_fmt_plug.c:334:3: warning: braces around scalar initializer [enabled by default]
nsec3_gen_fmt_plug.c:334:3: warning: (near initialization for ‘fmt_nsec3_gen.methods.binary_hash[1]’) [enabled by default]
nsec3_gen_fmt_plug.c:335:4: warning: initialization from incompatible pointer type [enabled by default]
nsec3_gen_fmt_plug.c:335:4: warning: (near initialization for ‘fmt_nsec3_gen.methods.binary_hash[1]’) [enabled by default]
nsec3_gen_fmt_plug.c:336:4: warning: excess elements in scalar initializer [enabled by default]
nsec3_gen_fmt_plug.c:336:4: warning: (near initialization for ‘fmt_nsec3_gen.methods.binary_hash[1]’) [enabled by default]
nsec3_gen_fmt_plug.c:337:4: warning: excess elements in scalar initializer [enabled by default]
nsec3_gen_fmt_plug.c:337:4: warning: (near initialization for ‘fmt_nsec3_gen.methods.binary_hash[1]’) [enabled by default]
nsec3_gen_fmt_plug.c:338:4: warning: excess elements in scalar initializer [enabled by default]
nsec3_gen_fmt_plug.c:338:4: warning: (near initialization for ‘fmt_nsec3_gen.methods.binary_hash[1]’) [enabled by default]
nsec3_gen_fmt_plug.c:340:3: warning: excess elements in scalar initializer [enabled by default]
nsec3_gen_fmt_plug.c:340:3: warning: (near initialization for ‘fmt_nsec3_gen.methods.binary_hash[1]’) [enabled by default]
nsec3_gen_fmt_plug.c:341:3: warning: initialization from incompatible pointer type [enabled by default]
nsec3_gen_fmt_plug.c:341:3: warning: (near initialization for ‘fmt_nsec3_gen.methods.binary_hash[2]’) [enabled by default]
nsec3_gen_fmt_plug.c:342:3: warning: initialization from incompatible pointer type [enabled by default]
nsec3_gen_fmt_plug.c:342:3: warning: (near initialization for ‘fmt_nsec3_gen.methods.binary_hash[3]’) [enabled by default]
nsec3_gen_fmt_plug.c:344:2: warning: initialization from incompatible pointer type [enabled by default]
nsec3_gen_fmt_plug.c:344:2: warning: (near initialization for ‘fmt_nsec3_gen.methods.binary_hash[4]’) [enabled by default]
make[1]: **\* [nsec3_gen_fmt_plug.o] Error 1
make[1]: Leaving directory `/tmp/john-1.8.0-jumbo-1/src'
make: **\* [default] Error 2

**Comment by anonion0** [comment]
Looks like JtR's plugin format changed slightly. It should be fixed by the latest commit. 
Thanks for reporting this issue!
