### ISSUE TITLE
"failed to import nsec3hash module" in docker

### ISSUE THREAD

**Issue by exander77** [anonion0/nsec3map#15]
When I build docker, I get this warning about fallback to Python hashing.

**Comment by anonion0** [comment]
That is because the Docker Python image we're using is based on Debian _stable_ (currently _bullseye_), which does not have OpenSSL 3 yet.
Perhaps we should just use the Debian _testing_ image (currently _bookworm_) instead.

This Dockerfile should work:

```dockerfile
FROM debian:bookworm

WORKDIR /usr/src/nsec3map
COPY . /usr/src/nsec3map

RUN apt-get -y update
RUN apt-get install -y libssl3 libssl-dev \
	python3 \
	python3-dev \
	python3-pip \
	python3-dnspython \
	python3-numpy \
	python3-scipy

RUN pip install .[predict]

WORKDIR /host
ENTRYPOINT ["n3map"]
```

**Comment by anonion0** [comment]
I added the new Dockerfile in 2e340a1 and it works.
