### ISSUE TITLE
Allow to auto-stop after N hashes generated

### ISSUE THREAD

**Issue by BenBE** [anonion0/nsec3map#18]
A small (and likely easy to implement) idea I was recently missing was a command line flag where I can tell n3map to generate at most a given number of hashes (like 2^30) and terminate at the time latest even if the zone hasn't been fully enumerated yet.

This feature can be interesting if you are enumerating several zones in a batch run and want a somewhat "guaranteed" runtime for each zone.

**Comment by anonion0** [comment]
Agreed. I wanted to add something along these lines at some point.

Similar options could be:
- Abort after `N` hashes tested w/o finding an uncovered one
- Abort at a certain hash coverage (bonus if it could estimate how long it would take to find another uncovered hash)

**Comment by BenBE** [comment]
Given that finding a hash inside a certain range is proportional to that range's size, you can estimate the number of (random) guesses by `2^-log(1-coverage)`. So if a quarter is currently still uncovered, you will likely be a random guess for that uncovered range in the next for guesses (not guaranteed, but with high probability).

This even could be used as a further termination option: Terminate if `log(1 - coverage) / log(coverage / #RR) > X` with `X > 2` (i.e. if the remaining gap in the coverage is significantly smaller than the average gap covered by each found RR so far).

**Comment by anonion0** [comment]
I decided to add an option `--hashlimit=N` to limit the # of hashes checked as you originally described. I may add more sophisticated termination options at some point, but I think for most scenarios this is probably sufficient.
