### ISSUE TITLE
Help with installation and usage

### ISSUE THREAD

**Issue by elidort** [anonion0/nsec3map#22]
I was wandering if someone can make just a short video on how to set it up and run it. I did as the installation Guide said but nothing, i also think, the installation Guide and usage is not detailed enough there need to be some updates to make things a little clear for be people who are not experts in DNS enumeration and all that. Thanks

**Comment by anonion0** [comment]
I'm not sure about making a video, but maybe we can include a short "Quick Start" guide.

Could you let us know where exactly you got stuck?

**Comment by elidort** [comment]
![1](https://user-images.githubusercontent.com/122856111/222520181-c4451a0b-f09b-4ed5-9ef7-4219c5d415ca.png)
![2](https://user-images.githubusercontent.com/122856111/222520247-0b33d716-4317-44c0-bbe3-51c09023bd0f.png)
![3](https://user-images.githubusercontent.com/122856111/222520271-0d08ac86-64c3-463e-91fb-9c98a5707c9a.png)

What i'm i missing??

**Comment by elidort** [comment]
![1](https://user-images.githubusercontent.com/122856111/222521096-f575c49e-8ef2-4cbb-b8a5-30fb0ab417de.png)
![2](https://user-images.githubusercontent.com/122856111/222521111-f1df3e8c-c2ed-43fd-9d4d-961de4b9270b.png)
![3](https://user-images.githubusercontent.com/122856111/222521122-545b39da-1795-4d4b-aa54-573ee71e8a22.png)

These are the errors i keep getting don't know why

**Comment by elidort** [comment]
I installed it.
I was missing some dependencies and also it requires python3.9 which wasn't specify in the README.
Aside that i had to install libssl-dev.
I was using Debian 20

**Comment by anonion0** [comment]
I think you were probably missing the python headers (`python3-dev` or similar), which are needed to compile the extension module.

I will clarify this in the README (also some other missing dependencies, like a C compiler...).

**Comment by anonion0** [comment]
> I will clarify this in the README (also some other missing dependencies, like a C compiler...).

done
