### ISSUE TITLE
optionally skip zones using commonly-used 'ab' salt

### ISSUE THREAD

**Issue by roycewilliams** [anonion0/nsec3map#4]
The "[white lies](https://tools.ietf.org/html/rfc7129#appendix-B)" technique of preventing NSEC3 enumeration appears to be strongly correlated with zones that use a simple 'ab' as the salt. From my testing across quite a few zones, no 'ab'-salted domains can be properly enumerated using nsec3map.

Recommendation: As a user-configurable option, perform a NSEC3PARAM lookup to query the salt in advance, and if it is 'ab', skip the zone.

$ host -t nsec3param geoguessr.com
geoguessr.com has NSEC3PARAM record 1 0 1 AB

Obviously, someone could simply use 'ab' as their salt to avoid enumeration. But this would also make their zone more easily bruteforced, as their salt would be short and static.

Edit: it's also possible that I'm totally wrong about it being "white lies". The static salt might instead just the sign of a front-end device with an unchanging salt that also happens to detect and block enumeration. For example, [Infoblox may have done this at some point](https://www.kirei.se/en/2013/09/23/infoblox-dnssec/).

**Comment by roycewilliams** [comment]
For reference/testing here are some zones that have an 'ab' salt. They are listed in Alexa order (of the sites I've been working with, anyway).

geoguessr.com
elevcentralen.se
coolstuff.se
nordichardware.se
gleerups.se
lonestatistik.se
tv-tabla.se
yungleangear.com
whitetrash.nl
rigpix.com
skl.se
spraktidningen.se
yh-antagning.se
athleteshop.nl
himatube.se
habrador.com
ljudbojen.com
tovek.se
nittygrittystore.com
svartgul.se
maxgaming.com
stunlockstudios.com
hjart-lungfonden.se
borent.nl
btcctb.org
simplysupplements.net
misslisibell.se
kbr.be
mazegenerator.net
diasp.org
lanstrafikenkron.se
112simulator.nl
listor.se
filmcafe.se
awesomeminer.com
utv.se
cosketch.com
bokio.se
scrapmechanic.com
superbilligt.se
buttericks.se
stocknavigator.ru
pixeltopic.com
modelbrouwers.nl
xn--krkortsfrgor-1cb3u.nu
time-team.nl
ponty-system.se
skodaforum.nl
frialigan.se
droider.eu

**Comment by roycewilliams** [comment]
Further analysis reveals that some 'ab'-salted zones are enumerated just fine. I suspect that what's happening is that a particular software suite or appliance both uses a static 'ab' and also has optional detection of enumeration. It may be that the response to enumeration can itself be detected and cleanly handled in some way. Still researching.

**Comment by anonion0** [comment]
If a zone truly uses NSEC3 "white lies", it should be fairly easy to detect by just checking the hash distance that an NSEC3 record covers. If the hash distance = 2, it is a minimally covering NSEC3 record, which should be extremely unlikely to exist in a zone that doesn't use white lies. Based on that, the enumeration could be aborted. A similar principle could be applied to detect [minimally-covering NSEC records](https://tools.ietf.org/html/rfc4470) in NSEC mode.

That being said, I haven't really encountered either of those two configurations out in the wild, I have no idea how common they actually are.

**Comment by anonion0** [comment]
By the way, I've noticed that some servers do sometimes omit sending NSEC3 records either as a measure to prevent enumeration or maybe just for performance reasons. I found that in practice this can often be handled by specifying a reduced query rate, e.g. using
 ```
n3map -v3p --limit-rate 50/s [zone]
```

**Comment by roycewilliams** [comment]
Ah, thanks for the explanation. My understanding of NSEC3 was exactly zero a couple of days ago, so I'm playing catchup. :)

I just checked, and in the survey I'm currently conducting (about 280K NSEC3-enabled zones so far), none of them have hashes anywhere near that close to each other. I'm also deliberately skipping all zones with an 'ab' salt right now, so this number _might_ be skewed ... but since the only "white lies" implementation I've been able to locate so far is Phreebird, and its author (Dan Kaminsky) would probably rather eat broken glass than use a short, static salt ... I suspect that these two things are totally unrelated.

It would probably still be academically interesting to detect "white lies" at some point, but I'll continue to try to narrow down why I have a strong correlation between 'ab' salts and enumeration caps/timeouts.

**Comment by roycewilliams** [comment]
Interesting data point: this other project's issue correlates 'ab' salt with "white lies": 

https://www.vs.uni-due.de/trac/dnssec/ticket/39
https://www.vs.uni-due.de/trac/dnssec/ticket/40

**Comment by roycewilliams** [comment]
Interesting about the query rate. Even though the test system is behind a 1Mb/s (!) connection, I would expect the natural threshold to be pretty high. Looking at the code, it doesn't look like there's a default cap? I resumed my process using 50/s, but it doesn't seem appreciably slower.

**Comment by anonion0** [comment]
Good point about Phreebird/Dan, I guess the 'AB' salt might still originate from a default configuration that operators are supposed to change? If a server actually uses white lies, I don't see a reason why a salt would be of any importance at all, since you wouldn't gain any information by (trying to) crack the NSEC3 hashes from such a server anyway.

**Comment by anonion0** [comment]
About the query rate: It's not capped by default, but the default way nsec3map operates is that it waits for a reply for each query until it sends another one. This is the only way it can be guaranteed that it uses a minimal number of requests to enumerate a zone. Hence, the query rate is mainly dependent on the latency you have to a particular nameserver.

If you don't care about making a few extra requests that might turn out to have been unnecessary, you can use the `--aggressive N` option, where N specifies the maximum number of requests to send in parallel. This can significantly speed up enumeration in practice (especially on high-latency connections), though it is advisable to use it in combination with `--limit-rate` in order to keep the server happy ;-)

**Comment by anonion0** [comment]
One more thing: If you are using nsec3map for your survey, you might also want to use the `--ignore-overlapping` option on large zones. This way, n3map won't terminate as soon as it receives an NSEC3 record that overlaps with another one. It makes the process significantly more robust on large zones (such as the TLD zones) which are constantly changing, where it's impossible to get a snapshot that doesn't contain overlapping records. I originally implemented it for this exact purpose.

The `-p`/`--predict` option might also be useful: it can help to estimate the size of a zone w/o enumerating it completely.

**Comment by anonion0** [comment]
Detection for minimally-covering NSEC3 records is implemented in 15040ae08c2927f449eca23c51c3700deb09d324 :
```
n3map: fatal: Received minimally-covering NSEC3 record
This zone likely uses "NSEC3 White Lies" to prevent zone enumeration
(See https://tools.ietf.org/html/rfc7129#appendix-B)
```

**Comment by roycewilliams** [comment]
Everything else looks to be working fine so far. If I encounter any evidence of White Lies, I'll report back. Thanks very much for the analysis and insight!

**Comment by roycewilliams** [comment]
To tie up one concept from the thread - the static 'ab' salt was why I originally jumped to the wrong conclusion, because I had deduced that salts wouldn't matter for White Lies. :)
