### ISSUE TITLE
excessive(?) "hit an existing owner name" output?

### ISSUE THREAD

**Issue by roycewilliams** [anonion0/nsec3map#5]
Using this syntax:

`n3map -v --ignore-overlapping --ldh --max-retries=1 --timeout=30000 --limit-rate 50/s -o [domain].out [domain]
`

...  (and using the latest n3map / map.py from Github), a couple of domains (for example, ladiada.com and karmelak.pl) go through a pretty extensive number of "hit an existing owner name" output lines:

```
$ head -20 karmelak.pl.debug
looking up nameservers for zone karmelak.pl.
using nameserver: 46.242.149.31:53 (dns3.home.pl.)
using nameserver: 46.242.149.30:53 (dns3.home.pl.)
using nameserver: 46.242.149.10:53 (dns.home.pl.)
using nameserver: 46.242.149.11:53 (dns.home.pl.)
using nameserver: 46.242.149.20:53 (dns2.home.pl.)
using nameserver: 46.242.149.21:53 (dns2.home.pl.)
checking SOA...
detecting zone type...
hit an existing owner name
hit an existing owner name
hit an existing owner name
hit an existing owner name
hit an existing owner name
hit an existing owner name
hit an existing owner name
hit an existing owner name
hit an existing owner name
hit an existing owner name
hit an existing owner name

$ wc -l karmelak.pl.debug
26877 karmelak.pl.debug

$ wc -l ladiada.com.debug
4341 ladiada.com.debug
```

**Comment by anonion0** [comment]
It seems this happens on zones that aren't DNSSEC-enabled and also use wildcards. Maybe I should add a DNSKEY lookup at the beginning to test whether the zone actually uses DNSSEC at all. I'll look into it.

**Comment by anonion0** [comment]
Check out 2ab86484eae22a50c50d27e152bcfc5c0dc3c127.
nsec3map now checks the zone's DNSKEY record before enumeration and aborts if it isn't there. I also added a switch `--omit-dnskey-check` if you want to disable the check on zones that you know are DNSSEC-enabled.

**Comment by roycewilliams** [comment]
Ah, interesting - I didn't even think to check for that. It turns out that both of these domains had DNSSEC enabled back in May, but it's now disabled. Thanks for the additional logic - I think it's a good general check to make.

**Comment by roycewilliams** [comment]
Here's one that does appear to currently be using DNSSEC, and has nsec3param, but still goes on for a long while (still running):

$ n3map -v -o primelendingvermont.com.out primelendingvermont.com
looking up nameservers for zone primelendingvermont.com.
using nameserver: 69.36.145.33:53 (a3.verisigndns.com.)
using nameserver: 209.112.113.33:53 (a1.verisigndns.com.)
using nameserver: 209.112.114.33:53 (a2.verisigndns.com.)
checking SOA...
checking DNSKEY...
detecting zone type...
hit an existing owner name
hit an existing owner name
hit an existing owner name
hit an existing owner name
hit an existing owner name
hit an existing owner name
hit an existing owner name
hit an existing owner name
hit an existing owner name
hit an existing owner name
^C

Let me know if I should submit a new issue for this one.

See also:

primelendingcorpuschristi.com
primelendingmontana.com
primelendingwisconsin.com

**Comment by anonion0** [comment]
This one is interesting! I'm fairly certain that this server/zone is misbehaving, but maybe I am missing something. It seems like it has DNSSEC enabled, and it is responding via wildcard expansion, but it doesn't include the (mandatory) NSEC/NSEC3 records that would need to be included in such a response (to prove that no explicit record was present at the queried name and that it was indeed an expansion of a wildcard). From https://tools.ietf.org/html/rfc5155#section-7.2.6 :

> 7.2.6.  Wildcard Answer Responses
> 
>    If there is a wildcard match for QNAME and QTYPE, then, in addition
>    to the expanded wildcard RRSet returned in the answer section of the
>    response, proof that the wildcard match was valid must be returned.
> 
>    This proof is accomplished by proving that both QNAME does not exist
>    and that the closest encloser of the QNAME and the immediate ancestor
>    of the wildcard are the same (i.e., the correct wildcard matched).
> 
>    To this end, the NSEC3 RR that covers the "next closer" name of the
>    immediate ancestor of the wildcard MUST be returned.  It is not
>    necessary to return an NSEC3 RR that matches the closest encloser, as
>    the existence of this closest encloser is proven by the presence of
>    the expanded wildcard in the response.

If I am right about this and it is indeed misbehaving, then there might be no other way to detect this other than adding an option to limit the number of retries.

**Comment by anonion0** [comment]
RFC7129 has an informal description of how the server *should* behave: https://tools.ietf.org/html/rfc7129#section-5.3

**Comment by anonion0** [comment]
12635372828ba33599dde3a9fdb71208584b1f11 helps to avoid the loop. I limited the number of zone type detection attempts to 5 by default. This can be overridden using `--detection-attempts=N`. 

Thanks for finding all these special cases ;-)
Just out of curiosity: are you also including NSEC zones in your survey? I'd be interested to know if you found any minimally-covering NSEC zones out there.

**Comment by roycewilliams** [comment]
Thanks - working well to keep things moving along. I do have multiple instances running as well.

And glad to help with the corner cases! There may be more. :)

My survey is currently NSEC3-specific, because that's the "seed" data set that was already available - a list of NSEC3-looking domains - that I could cheat off of. I'm not really built out to go hunting for them myself at any scale. :) Though now that I think about it, since masscan supports sending of arbitrary PCAP payloads, I could probably rig up an NSEC3PARAM query. Then I'd just need more bandwidth than my 1Mbit connection. :)
