### ISSUE TITLE
feature request: save/resume state on late server timeout

### ISSUE THREAD

**Issue by roycewilliams** [anonion0/nsec3map#6]
As a nice-to-have:

If zone enumeration successfully started, and some records have been acquired, but the server then times out, it may be due to temporary throttling. If current state could be saved to a specified file, and then a flag added to resume if the specified file exists (so two different new command-line options), then zones could be eventually fully enumerated (or at least moreso).

Edit: On the next run, the user could potentially adjust the query rate downwards to compensate (if that was the issue).

**Comment by anonion0** [comment]
I think this should be sufficiently covered by the `-c` / `--continue` option, especially with the recent improvements making it more convenient (it'll create the file if it doesn't already exist now) and safer (w.r.t. data loss).

However, what would be nice to have is a feature to detect rate throttling and to automatically adjust the query rate...
