### ISSUE TITLE
Ignore mis-behaving authoritative servers

### ISSUE THREAD

**Issue by BenBE** [anonion0/nsec3map#7]
Some DNS servers (e.g. in the nl. or fail. zones) sometimes omit DNSSEC-relevant records causing nsec3map to hard-fail on the zone although asking one of the other servers for the same record would work just fine. This is especially annoying as this causes the reload of a large state file when iterating such zones.

Currently binding nsec3map to one of the servers will usually solve the issue.

Intended behaviour: Retry with different server and only fail if all lack DNSSEC RR and no particular "brute-force-anyway" option is given.

**Comment by anonion0** [comment]
This is (finally) addressed in 8b5a4df.

It adds an option `--max-errors` which specifies how many (consecutive) erroneous responses from a particular server are tolerated until it is ignored (i.e. removed from the list of nameservers). If a query fails once it is sent to the next nameserver, so typically, multiple different queries would need to fail for a server to be removed if `--max-errors` is > 1.
It also applies to things like `SERVFAIL` errors.

`--max-errors=-1` is the brute-force option.
